version: '3.1'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: world
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
